databases:
  - name: microverse
    databaseName: my_app
    user: victoira

services:
  - type: web
    name: my_budget_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microverse
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false